#!/bin/bash
# =====================================================
# BhumiShop - Quick Interactive Fix Guide
# =====================================================

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║   BhumiShop - Supabase RLS Fix Guide                ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "The '0 produtos' issue is caused by Row Level Security (RLS)"
echo "policies blocking anonymous read access to your database."
echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  STEP 1: Open Supabase Dashboard                    │"
echo "└──────────────────────────────────────────────────────┘"
echo ""
echo "  URL: https://app.supabase.com/project/pyidnhtwlxlyuwswaazf"
echo ""
read -p "  Press Enter when you've opened the dashboard..."

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  STEP 2: Go to SQL Editor                           │"
echo "└──────────────────────────────────────────────────────┘"
echo ""
echo "  1. Click 'SQL Editor' in the left sidebar"
echo "  2. Click '+ New Query' button"
echo ""
read -p "  Press Enter when you've opened SQL Editor..."

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  STEP 3: Copy and Run SQL                           │"
echo "└──────────────────────────────────────────────────────┘"
echo ""
echo "  The SQL file is at: fix_rls_policies.sql"
echo ""
echo "  Run this command to display it:"
echo "    cat fix_rls_policies.sql"
echo ""
echo "  Then copy the output and paste it into SQL Editor."
echo ""
read -p "  Press Enter once you've pasted and RUN the SQL..."

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  STEP 4: Verify Policies                            │"
echo "└──────────────────────────────────────────────────────┘"
echo ""
echo "  After running, you should see output showing 6 policies:"
echo "    - Allow public read access to products"
echo "    - Allow admin full access to products"
echo "    - Allow public read access to categories"
echo "    - Allow admin full access to categories"
echo "    - Allow public read access to collections"
echo "    - Allow admin full access to collections"
echo ""
read -p "  Press Enter once you've confirmed the policies..."

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  STEP 5: Test the App                               │"
echo "└──────────────────────────────────────────────────────┘"
echo ""
echo "  1. Clear browser cache: Ctrl+Shift+Delete"
echo "  2. Restart dev server: npm run dev"
echo "  3. Go to: http://localhost:5173/produtos"
echo "  4. Check if products load"
echo ""
echo "  If products still don't load, check browser console (F12)"
echo "  for error messages."
echo ""
echo "══════════════════════════════════════════════════════"
echo "  Service Role Rotation (Optional)"
echo "══════════════════════════════════════════════════════"
echo ""
echo "  Only rotate if you suspect the key is compromised."
echo ""
echo "  1. Go to: https://app.supabase.com/project/pyidnhtwlxlyuwswaazf/settings/api"
echo "  2. Scroll to 'Project API keys'"
echo "  3. Find 'service_role' key"
echo "  4. Click 'Rotate' or 'Regenerate'"
echo "  5. Copy new key immediately"
echo ""
echo "  NOTE: The anon key is valid until 2036, no rotation needed."
echo ""
echo "Done! If you need more help, see SUPABASE_FIX_INSTRUCTIONS.md"
echo ""
